version: '3.7'
services:
  app:
    image: node:12.22.9
    container_name: payments_app
    working_dir: /usr/src/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
    ports:
      - '50051:50051'
    volumes:
      - .:/usr/src/app
    links:
      - db:db
    entrypoint: bash -c ./start.sh
  db:
    image: postgres:latest
    container_name: db_payments
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -P password"]
      interval: 10s
      timeout: 5s
      retries: 5